CREATE DATABASE DAY2;
USE DAY2;

CREATE TABLE PERSON(
ROLL_NO INT PRIMARY KEY  NOT NULL AUTO_INCREMENT,
NAME VARCHAR(32),
CLASS INT,
ADDRESS VARCHAR(10),
AGE INT
);

INSERT INTO PERSON VALUE(DEFAULT,'AKSH',4,'19Z',9);
INSERT INTO PERSON VALUE(DEFAULT,'GIVIN',5,'14K',10);
INSERT INTO PERSON VALUE(DEFAULT,'GRIFIN',9,'6L',11);

-- PRACTICE DAY 1
SELECT * FROM PERSON;
SELECT NAME,CLASS FROM PERSON;
SELECT NAME,ROLL_NO FROM PERSON WHERE AGE>=10;
SELECT * FROM PERSON WHERE NAME='GIVIN';
UPDATE PERSON SET AGE=19 WHERE NAME='AKSH';
SELECT * FROM PERSON;

START TRANSACTION; 
DELETE FROM PERSON WHERE AGE=11;
select * FROM PERSON;
ROLLBACK;
SELECT * FROM PERSON;


-- DAY -2
SELECT DISTINCT NAME,AGE FROM PERSON ;
SELECT * FROM PERSON WHERE AGE>=10 AND CLASS>5;

SELECT * FROM PERSON ORDER BY NAME DESC LIMIT 2;